services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  bff:
    build:
      context: ./bff-controle-escolar
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
